apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-auth-helper
spec:
  schedule: "0 */12 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 30
      template:
        spec:
          serviceAccountName: ecr-auth-helper
          containers:
          - name: ecr-auth-helper
            image: slepnevns/ecr-auth-helper:x86
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: ecr-auth-helper-config
            - secretRef:
                name: ecr-auth-helper-secret
          restartPolicy: OnFailure