kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: develop
  name: ecr-auth-helper
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - serviceaccounts
      - serviceaccounts/token
    verbs:
      - 'delete'
      - 'create'
      - 'patch'
      - 'get'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-auth-helper
  namespace: develop
subjects:
  - kind: ServiceAccount
    name: ecr-auth-helper
    namespace: develop
roleRef:
  kind: Role
  name: ecr-auth-helper
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-auth-helper
  namespace: develop